[package]
name = "flowlab-client"
version.workspace = true
description.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
flowlab-core = { path = "../core" }
