- instruction: Set display units
  device: 612A
  parameters:
    - name: channel
      value: CHA
    - name: units
      value: K
- instruction: Set temperature
  device: 612A
  parameters:
    - name: channel
      value: CHA
    - name: value
      value: 2
    - name: rate
      value: 10
- instruction: Wait for
  metric: 
    instruction: Get temperature
    device: 612A
    parameters:
      - name: channel
        value: CHA
  parameters:
    value: 2
    tolerance: 0.1 # absolute tolerance
    delay: 120 # seconds
- instruction: Set display units
  device: 4G
  parameters:
    - name: units
      value: T
- instruction: Set field
  device: 4G
  parameters:
    - name: value
      value: 0
    - name: unit
      value: T
- instruction: Scan
  metric: 
    instruction: Set temperature
    device: 612A
    parameters:
      - name: channel
        value: CHA
      - name: rate
        value: 10
  type: settle
  parameters:
    variable: value
    start: 2
    stop: 300
    step: 1
  datafile: /tmp/datafile.csv
  measures:
    - instruction: Get temperature
      device: 612A
      parameters:
        - name: channel
          value: CHA