# 3_Model 4G Instruction Manual - Rev 9_0.pdf
instructions:
  - name: Set module
    command:
      query: "CHAN {{module}}\n"
      parameters:
        - name: module
          type: integer
          values:
            - 1
            - 2
    description: Selects the module for subsequent remote commands. A command error is returned if only one module is installed.
  - name: Get module
    command:
      query: "CHAN?\n"
    response:
      format: "{{module}}"
      parameters:
        - name: module
          type: integer
          values:
            - 1
            - 2
    description: Returns the power module currently selected for remote commands. It returns 1 or 2. A command error is returned if only one module is installed.
  - name: Set error response mode
    command:
      query: "ERROR {{mode}}\n"
      parameters:
        - name: mode
          type: integer
          values:
            - 0
            - 1
          description: 0 = disable error reporting, 1 = enable error reporting
    description: Enables or disables error messages when the USB interface is used. It is much easier to handle errors under program control when using the USB interface if error messages are disabled, but it is desirable to enable error messages if a terminal program is used to interactively control and query the 4G.
  - name: Get error response mode
    command:
      query: "ERROR?\n"
    response:
      format: "{{mode}}"
      parameters:
        - name: mode
          type: integer
          values:
            - 0
            - 1
          description: 0 = disable error reporting, 1 = enable error reporting
    description: Returns the selected error reporting mode.
  - name: Set field
    command:
      query: "IMAG {{field}}\n"
      parameters:
        - name: field
          type: float
          default: 0.0
    description: Sets the magnet current shown on the display. The supply must be in standby or a command error will be returned. The value must be supplied in the selected units - amperes or field (kG). If Shim Mode is enabled, the persistent mode current displayed for the named shim is set if the shim parameter is provided.
  - name: Get magnet current
    command:
      query: "IMAG?\n"
    response:
      format: "{{magnet_current}} {{units}}" # VERIFY
      parameters:
        - name: magnet_current
          type: float
        - name: units
          type: string
          values:
            - A
            - kG
    description: Returns the magnet current (or magnetic field strength) in the present units. If the persistent switch heater is ON the magnet current returned will be the same as the power supply output current. If the persistent switch heater is off, the magnet current will be the value of the power supply output current when the persistent switch heater was last turned off. The magnet current will be set to zero if the power supply detects a quench.
  - name: Get power supply output current
    command:
      query: "IOUT?\n"
    response:
      format: "{{output_current}}{{units}}"
      parameters:
        - name: output_current
          type: float
        - name: units
          type: string
          values:
            - A
            - G
    description: Returns the power supply output current (or magnetic field strength) in the present units.
  - name: Set current sweep lower limit
    command:
      query: "LLIM {{limit}}\n"
      parameters:
        - name: limit
          type: float
          default: 0.0
    description: Sets the current limit used when the next SWEEP DOWN command is issued. The value must be supplied in the selected units - amperes or field (kG). An error will be returned if this value is greater than the upper sweep limit.
  - name: Get current sweep lower limit
    command:
      query: "LLIM?\n"
    response:
      format: "{{limit}} {{units}}"
      parameters:
        - name: limit
          type: float
        - name: units
          type: string
          values:
            - A
            - kG
    description: Returns the current limit used when the next SWEEP DOWN command is issued.
  - name: Return control to front panel
    command:
      query: "LOCAL\n"
    description: Returns control of the device to the front panel. RS-232 only.
  - name: Get selected operating mode
    command:
      query: "MODE?\n"
    response:
      format: "{{mode}}"
      parameters:
        - name: mode
          type: string
          values:
            - Shim
            - Manual
    description: Returns the selected operating mode.
  - name: Set magnet coil name
    command:
      query: "NAME {{name}}\n"
      parameters:
        - name: name
          type: string
    description: Sets the name of the magnet coil. The name is displayed on the front panel display.
  - name: Get magnet coil name
    command:
      query: "NAME?\n"
    response:
      format: "{{name}}"
      parameters:
        - name: name
          type: string
    description: Returns the name of the magnet coil.
  - name: Control persistent switch heater
    command:
      query: "PSHTR {{state}}\n"
      parameters:
        - name: state
          type: string
          values:
            - "ON"
            - "OFF"
    description: Turns the persistent switch heater on or off. The persistent switch heater is used to maintain the magnet current when the power supply is in standby mode. The persistent switch heater is automatically turned off when the power supply is turned on.
  - name: Get persistent switch heater state
    command:
      query: "PSHTR?\n"
    response:
      format: "{{state}}"
      parameters:
        - name: state
          type: boolean
          values:
            - 0
            - 1
    description: Returns the state of the persistent switch heater. If in Shim Mode, the status of the switch heater for the selected shim is returned.
  - name: Reset quench condition
    command:
      query: "QRESET\n"
    description: Resets a power supply quench condition and returns the supply to STANDBY.
  - name: Set range limit for sweep rate boundary
    command:
      query: "RANGE {{range}} {{limit}}\n"
      parameters:
        - name: range
          type: integer
          values:
            - 0
            - 1
            - 2
            - 3
            - 4
          description: Do not use any other value besides 0 unless you know what you are doing.
        - name: limit
          type: float
          description: Make sure to not set a limit that is greater than the maximum rate of the power supply.
    description: Sets the upper limit for a charge rate range in amps.  Range 0 starts at zero and ends at the limit provided. Range 1 starts at the Range 0 limit and ends at the Range 1 limit provided. Range 2 starts at the Range 1 limit and ends at the Range 2 limit provided. Range 3 starts at the Range 2 limit and ends at the Range 3 limit provided. Range 4 starts at the Range 3 limit and ends at the supply output capacity.
  - name: Get range çimit for sweep rate boundary
    command:
      query: "RANGE? {{range}}\n"
      parameters:
        - name: range
          type: integer
          values:
            - 0
            - 1
            - 2
            - 3
            - 4
    response:
      format: "{{range}}"
    description: Returns the upper limit for a charge rate range in amps.
  - name: Set sweep rate
    command:
      query: "RATE {{rate}} {{sweep_rate}}\n"
      parameters:
        - name: rate
          type: integer
          values:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
          description: Do not use any other value besides 0 unless you know what you are doing.
        - name: sweep_rate
          type: float
          description: Make sure to not set a sweep rate that is greater than the maximum rate of the power supply per each magnetic field range.
    description: Sets the charge rate in amps/second for a selected range. A range parameter of 0, 1, 2, 3, and 4 will select Range 1, 2, 3, 4, or 5 sweep rates as displayed in the Rates Menu. A range parameter of 5 selects the Fast mode sweep rate.DOWN command.
  - name: Get range limit for sweep rate boundary
    command:
      query: "RATE? {{range}}\n"
      parameters:
        - name: range
          type: integer
          values:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
    response:
      format: "{{sweep_rate}}"
      parameters:
        - name: sweep_rate
          type: float
    description: Queries the charge rate in amps/second for a selected range. A range parameter of 0 to 4 will select Range 1 through 5 sweep rates as displayed in the Rates Menu. A range parameter of 5 queries the Fast mode sweep rate.
  - name: Select remote operation mode
    command:
      query: "REMOTE\n"
    description: Takes control of the 4G via the remote interface. All buttons on the front panel are disabled except the Local button. This command will be rejected if the menu system is being accessed via the front panel or if LOCAL has been selected via the Local button on the front panel. Pressing the Local button again when the menu is not selected will allow this command to be executed. This command is only necessary for USB operation since the IEEE-488 interface provides for bus level control of the Remote and Lock controls.
  - name: Set units
    command:
      query: "UNITS {{units}}\n"
      parameters:
        - name: units
          type: string
          values:
            - A
            - G
          default: G
    description: Sets the units to be used for all input and display operations. Units may be set to Amps or Gauss. The unit will autorange to display Gauss, Kilogauss or Tesla.
  - name: Select SHIM
    command:
      query: "SHIM {{status}} {{selection}}\n"
      parameters:
        - name: status # Optional
          type: string
          values:
            - Enable
            - Disable
        - name: selection
          type: string
          values:
            - Z
            - Z2
            - Z3
            - Z4
            - X
            - Y
            - ZX
            - ZY
            - C2
            - S2
            - Z2X
            - Z2Y
            - All
    description: Selects a shim to be controlled or queried.  It also allows selected shims or all shims to be disabled or enabled. The command is only valid when operating in SHIM mode. The switch heater must be off when making a shim selection.

  # Meta instructions
  - name: Get field
    command:
      query: "IMAG?; LOCAL\n"
    response:
      format: "{{magnet_current}} {{units}}"
      parameters:
        - name: magnet_current
          type: float
        - name: units
          type: string
          values:
            - A
            - kG
    description: Queries the magnetic field strength and returns control to the front panel.
  - name: Set field with sweep rate
    command:
      query: "REMOTE; UNIT G; RATE 0 {{sweep_rate}}; {% if field > 0 %}ULIM {{field}}; SWEEP UP{% elif field < 0 %}LLIM {{field}}; SWEEP DOWN{% else %}SWEEP ZERO{% endif %}; LOCAL\n"
      parameters:
        - name: sweep_rate
          type: float
        - name: field
          type: float
    description: Sets the magnetic field strength with a sweep rate and returns control to the front panel.
