# SCPI/IEEE-488.2 Common Commands
instructions:
  - name: Device information
    command:
      query: "*IDN?\n"
    response:
      format: "{{manufacturer}},{{model}},{{serial_number}},{{firmware_version}}"
      parameters:
        - name: manufacturer
          type: string
        - name: model
          type: string
        - name: serial_number
          type: integer
        - name: firmware_version
          type: string
        # - name: build number
        #   type: integer
    description: Returns the manufacturer, model number, serial number, and firmware version of the device.
  - name: Reset the device
    command:
      query: "*RST\n"
    description: Reset the instrument. Depending on the instrument, this may reset the device to a known state or reboot the device.
