# SCPI/IEEE-488.2 Common Commands
instructions:
  - name: Device information
    command:
      query: "*IDN?"
    response:
      format: "{{identification}}"
      parameters:
        - name: identification
          type: string
        # - name: manufacturer
        #   type: string
        # - name: model
        #   type: string
        # - name: serial number
        #   type: integer
        # - name: firmware version
        #   type: string
        # - name: build number
        #   type: integer
    description: Returns the manufacturer, model number, serial number, and firmware version of the device.
  - name: Reset the device
    command:
      query: "*RST"
    description: Reset the instrument. Depending on the instrument, this may reset the device to a known state or reboot the device.
