# SCPI/IEEE-488.2 Common Commands
- instruction: Identify the device
  alias:
    - Device information
  command:
    query: "*IDN?"
  response:
    - attribute: manufacturer
      type: string
    - attribute: model
      type: string
    - attribute: serial number
      type: integer
    - attribute: firmware version
      type: string
    - attribute: build number
      type: integer
  description: Returns the manufacturer, model number, serial number, and firmware version of the device.
- instruction: Reset the device
  command:
    query: "*RST"
  description: Reset the instrument. Depending on the instrument, this may reset the device to a known state or reboot the device.