- name: 612
  protocol:
    ip: 192.168.1.2
    port: 5000
  instruction:
    - scpi
    - 612
- name: 612A
  protocol:
    ip: 192.168.1.2
    port: 5000
  instruction:
    - scpi
    - 612
  default_arguments:
    - name: channel
      value: CHA
    - name: units
      value: K
- name: 612B
  protocol:
    ip: 192.168.1.2
    port: 5000
  instruction:
    - scpi
    - 612
  default_arguments:
    - name: channel
      value: CHB
    - name: units
      value: K
