# This is a template for a device configuration file. It is used to create new devices.

# We start a list of devices. This can be repeated in multiple places and the records will be merged. If the same device is defined in multiple places, the last definition will be used.
devices:
  # The name is used as an identifier for the device. It should be unique.
  - name: DeviceName
    # The description is a human-readable description of the device. It is optional.
    description: Device Description
    # The protocol is a dictionary with the connection information for the device. It may vary depending on the protocol used to communicate with the device.
    # Here we have an example of a TCP/IP connection.
    protocol:
      ip: 192.168.1.1
      port: 1234
    # The instructions is a list of instructions that can be executed on the device.
    instructions:
      # We can use the path to an instruction file to include the instructions from that file. This can be relative to the current file or an absolute path.
      - path: ../instructions/instruction.yaml
      # We can also define instructions directly in the device configuration file.
      - name: Instruction Name
        # The command is the actual command that will be sent to the device. It is a dictionary with the query and response fields.
        command:
          query: "query {{argument1}} {{argument2}}"
          parameters:
            - name: argument1
              description: Description of argument 1
            - name: argument2
              description: Description of argument 2
        response:
          - name: response_name
            type: response_type
            values:
              - value1
              - value2
            description: Description of response
        # The description is a human-readable description of the instruction. It is optional.
        description: Instruction Description
      # Lastly, you can reference instructions defined on the same file but in an instructions section.
      - instruction: Another Instruction Name
    # The default_arguments is a list of default arguments that can be used in the instructions.
    default_arguments:
      - name: argument1
        value: default_value
        description: Description of argument 1
      - name: argument2
        value: default_value
        description: Description of argument 2
  # Add more devices here...
  - ...
