devices:
  - name: TM612
    description: Temperature Monitor 612
    protocol:
      ip: 192.168.1.3
      port: 5000
    instructions:
      - path: ./config/instructions/SCPI.yaml
      - path: ./config/instructions/TM612.yaml
  - name: TM612A
    description: Temperature Monitor 612 - Channel A - Shield
    protocol:
      ip: 192.168.1.3
      port: 5000
    instructions:
      - path: ./config/instructions/SCPI.yaml
      - path: ./config/instructions/TM612.yaml
    default_arguments:
      - name: channel
        value: A
      - name: units
        value: K
  - name: TM612B
    description: Temperature Monitor 612 - Channel B - Magnet
    protocol:
      ip: 192.168.1.3
      port: 5000
    instructions:
      - path: ./config/instructions/SCPI.yaml
      - path: ./config/instructions/TM612.yaml
    default_arguments:
      - name: channel
        value: B
      - name: units
        value: K
